---

- name: create directories for camac installation
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ camac_php_docroot }}"
    - "{{ camac_php_datadir }}"

- name: copy camac webroot to apache docroot
  synchronize:
    src: "{{ camac_releasedir }}/camac/{{ item.src }}"
    dest: "{{ item.dest }}"
    delete: yes
    rsync_opts: "{{ item.rsync_opts | d() }}"
  delegate_to: "{{ inventory_hostname }}"
  with_items:
    - src: "camac/public/"
      dest: "{{ camac_php_docroot }}"
    - src: "camac/"
      dest: "{{ camac_php_libdir }}"
    - src: "configuration/"
      dest: "{{ camac_php_confdir }}"

- name: copy CA chain to config path
  copy:
    content: "{{ camac_ca_chain }}"
    dest: "{{ camac_php_confdir }}/ca.pem"
  when: camac_ca_chain | d(false)

- name: configure php for CA chain
  copy:
    content: |
      ; config for camac CA chain
      openssl.cafile = "{{ camac_confdir }}/ca.pem"
    dest: "/etc/php/7.0/apache2/conf.d/99-quovadis-ssl-chain.ini"
  when: camac_ca_chain | d(false)

- name: prepare php prepend file
  copy:
    content: |
      <?php
      putenv('APPLICATION_PATH={{ camac_php_libdir }}/application');
      putenv('APPLICATION_ENV={{ camac_env }}');
      putenv('APPLICATION={{ camac_application }}');
      {% if camac_mock_tls %}
      $_SERVER['HTTPS'] = true;
      {% endif %}
    dest: "{{ camac_php_confdir }}/prepend.php"

- name: ensure public configuration symlink points to actual config directory
  file:
    state: link
    src: "{{ camac_php_confdir }}/public"
    path: "{{ camac_php_docroot }}/public"

- name: ensure application configuration symlink points to actual config directory
  file:
    state: link
    src: "{{ camac_php_confdir }}"
    dest: "{{ camac_php_libdir }}/configuration"

- name: make camac dirs writable
  file:
    state: directory
    owner: "{{ camac_apache_user }}"
    dest: "{{ item }}"
  with_items:
    - "{{ camac_php_datadir }}"
    - "{{ camac_php_tmpdir }}/mpdf"
    - "{{ camac_php_logdir }}"

- name: configure camac php app
  template:
    src: "application.ini.j2"
    dest: "{{ camac_php_confdir }}/configs/application.local.ini"
